import type { Dictionary } from 'style-dictionary/types';

import { formatDate } from '@iziui/toolkit/date';

import * as constModule from '../../consts';
import { defineFormatterPlugin } from '../defineFormatterPlugin';

const TOKEN_GROUPS = [
  { key: 'shape', title: 'Shape' },
  { key: 'grid', title: 'Grid' },
  { key: 'media-query', title: 'Breakpoints' },
  { key: 'behaviors', title: 'Visual Behavior' },
];

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function formatJavaScriptName(path: string[]) {
  const name = path
    .slice(1)
    .map(segment => segment
      .split('-')
      .map(piece => capitalize(piece))
      .join(''))
    .join('');

  return name.charAt(0).toLowerCase() + name.slice(1);
}

function formatStaticValue(value: unknown) {
  if (Array.isArray(value)) {
    return `\`${JSON.stringify(value)}\``;
  }

  if (typeof value === 'object' && value !== null) {
    return `\`${JSON.stringify(value)}\``;
  }

  return `\`${value}\``;
}

function formatTokenValue(value: unknown) {
  return `\`${String(value).replaceAll('|', '\\|')}\``;
}

function formatTokenGroup(dictionary: Dictionary, key: string, title: string) {
  const tokens = dictionary.allTokens.filter(token => token.path[0] === key);

  if (tokens.length === 0) { return ''; }

  const rows = tokens.map((token) => {
    const name = token.path.slice(1).join('-');
    const sassName = token.path.slice(1).join('-');

    // eslint-disable-next-line
    return `| \`${name}\` | \`${formatJavaScriptName(token.path)}\` | \`$${sassName}\` | ${formatTokenValue(token.value)} |`;
  });

  return [
    `## ${title}`,
    '',
    '| Token | JavaScript | Sass | Value |',
    '| --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export default defineFormatterPlugin(() => {
  return {
    name: 'markdown/token-reference',
    format: ({ dictionary }) => {
      const tokenGroups = TOKEN_GROUPS
        .map(({ key, title }) => formatTokenGroup(dictionary, key, title))
        .filter(Boolean);
      const staticRows = Object.entries(constModule)
        .map(([name, value]) => `| \`${name}\` | ${formatStaticValue(value)} |`);

      return [
        '# Token Reference',
        '',
        '> Auto-generated by `yarn workspace @iziui/tokens build`. Do not edit directly. ' + formatDate(new Date(), {
          locale: 'en-US',
          options: {
            day: '2-digit',
            month: '2-digit',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit'
          }
        }),
        '',
        'Use [README.md](README.md) for consumption examples and ownership guidance.',
        '',
        ...tokenGroups,
        '',
        '## Collections and Constants',
        '',
        '| Export | Value |',
        '| --- | --- |',
        ...staticRows,
        '',
      ].join('\n');
    },
  };
});
