
import type { Dictionary, TransformedToken } from 'style-dictionary';

import { defineFormatterPlugin } from '../defineFormatterPlugin';

function finder(tokens: TransformedToken[]) {
  return {
    get: (path: string, fallback: number) => {
      const token = tokens.find(t => t.path.join('.') === path);
      return token?.value ?? fallback;
    }
  };
}

function grid(dictionary: Dictionary) {
  const _finder = finder(dictionary.allTokens);

  const gapDefault = _finder.get('grid.gap', 0);
  const colsDefault = _finder.get('grid.columns', 12);
  const rowsDefault = _finder.get('grid.rows', 1);

  return `
/* GRID */
@mixin grid($gap: ${gapDefault}, $grid-columns: ${colsDefault}, $grid-rows: ${rowsDefault}) {
  width: 100%;
  display: grid;
  gap: $gap;
  position: relative;
  grid-template-rows: $grid-rows;
  grid-template-columns: repeat($grid-columns, 1fr);
  -ms-grid-columns: string.unquote(repeater("1fr ", $grid-columns));
}

@mixin grid-column-start($cols) {
  -ms-grid-column: $cols;
  grid-column-start: $cols;
}

@mixin grid-column-span($cols: $grid-columns) {
grid-column-end: span $cols;
-ms-grid-column-span: $cols;
}

@mixin grid-row-start($rows) {
  -ms-grid-row: $rows;
  grid-row-start: $rows;
}`;
}

function mediaQuery(dictionary: Dictionary) {
  const _finder = finder(dictionary.allTokens);

  const xl = _finder.get('media-query.xl', 0);
  const lg = _finder.get('media-query.lg', 12);
  const md = _finder.get('media-query.md', 1);
  const sm = _finder.get('media-query.sm', 1);
  const xs = _finder.get('media-query.xs', 1);

  return `
/* MEDRIA QUERY */
@mixin for-xl {
  @media only screen and (min-width: ${xl}px) {
    @content;
  }
}

@mixin for-lg {
  @media only screen and (max-width: ${lg}px) {
    @content;
  }
}

@mixin for-md {
  @media only screen and (max-width: ${md}px) {
      @content;
  }
}

@mixin for-sm {
  @media only screen and (max-width: ${sm}px) {
      @content;
  }
}

@mixin for-xs {
  @media only screen and (max-width: ${xs}px) {
    @content;
  }
}`;
}

export default defineFormatterPlugin(() => {
  return {
    name: 'scss/custom-mixins',
    format: ({ dictionary }) => {
      return [
        `/* Auto-generated by Style Dictionary. Do not edit directly. */
@use "sass:string";`,
        grid(dictionary),
        mediaQuery(dictionary),
      ].join('\n\n');
    }
  };
});
